version: '2'

services:
    app:
        image: node:6
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        command: scripts/entrypoint.sh node index.js
        ports:
            - "8081:80"
        environment:
            - FIRST_NAME=Keyboard
            - LAST_NAME=Cat
            - GRAVATAR_URL=https://media.giphy.com/media/10RhccNxPSaglW/giphy.gif
            - PORT=80