version: '2'

services:
    app:
        build: .
        working_dir: /usr/src/app
        volumes:
            - .:/usr/src/app
        command: scripts/entrypoint.sh node index.js
        ports:
            - "8080:80"
        environment:
            - PORT=80
            - CONSUL_ENDPOINT=consul
            - CONSUL_PORT=8500
            - ENVIRONMENT=development
    consul:
        image: consul:0.8.4
        volumes:
            - ./consul:/consul
        command: consul agent -config-dir /consul/config
        ports:
            - "8500:8500"
    